name: Get Unity license activation file ğŸ”

on:
  workflow_dispatch

jobs:
  unity_activate:
    runs-on: ubuntu-latest
    steps:
      - name: Unity - Activate
        uses: game-ci/unity-activate@v2.0.0